import { Business, Employee, Task } from '../types/api';
import { PFP_PRESETS } from './pfpPresets';

export const DEMO_BUSINESS: Business = {
  id: 'b0a1c2d3-e4f5-4a6b-8c9d-0e1f2a3b4c5d',
  name: 'PrintWorks Studio',
  category: 'Printing and design',
  timezone: 'Asia/Kolkata',
  created_at: '2026-09-27T06:00:00Z',
};

export const DEMO_EMPLOYEES: Employee[] = [
  {
    id: 'e1-asha',
    business_id: DEMO_BUSINESS.id,
    name: 'Asha Sharma',
    role: 'OWNER',
    department: 'Management',
    email: 'asha@printworks.studio',
    is_active: true,
    created_at: '2026-09-27T06:00:00Z',
    avatar_color: '#222321',
    avatar_url: PFP_PRESETS[0].url,
    initials: 'AS',
  },
  {
    id: 'e2-riya',
    business_id: DEMO_BUSINESS.id,
    name: 'Riya Patel',
    role: 'MANAGER',
    department: 'Design',
    email: 'riya.design@printworks.studio',
    is_active: true,
    created_at: '2026-09-27T06:00:00Z',
    avatar_color: '#EC4899',
    avatar_url: PFP_PRESETS[1].url,
    initials: 'RP',
  },
  {
    id: 'e3-arjun',
    business_id: DEMO_BUSINESS.id,
    name: 'Arjun Mehta',
    role: 'EMPLOYEE',
    department: 'Operations',
    email: 'arjun.ops@printworks.studio',
    is_active: true,
    created_at: '2026-09-27T06:00:00Z',
    avatar_color: '#0284C7',
    avatar_url: PFP_PRESETS[2].url,
    initials: 'AM',
  },
  {
    id: 'e4-neha',
    business_id: DEMO_BUSINESS.id,
    name: 'Neha Roy',
    role: 'EMPLOYEE',
    department: 'Customer Care',
    email: 'neha.care@printworks.studio',
    is_active: true,
    created_at: '2026-09-27T06:00:00Z',
    avatar_color: '#10B981',
    avatar_url: PFP_PRESETS[3].url,
    initials: 'NR',
  },
  {
    id: 'e5-karan',
    business_id: DEMO_BUSINESS.id,
    name: 'Karan Dave',
    role: 'EMPLOYEE',
    department: 'Dispatch & Print',
    email: 'karan.fleet@printworks.studio',
    is_active: true,
    created_at: '2026-09-27T06:00:00Z',
    avatar_color: '#F59E0B',
    avatar_url: PFP_PRESETS[4].url,
    initials: 'KD',
  },
];

// Helper to get timestamps relative to today so the demo is always fresh and exhibits the attention rules
function getRelativeDate(dayOffset: number, hour = 14, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-101',
    business_id: DEMO_BUSINESS.id,
    title: 'Finish monthly reporting & revenue breakdown',
    description: 'Compile Q3 print run metrics and submit to management.',
    assignee_id: 'e1-asha',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    due_at: getRelativeDate(0, 17, 0), // Today
    category: 'Operations',
    created_at: getRelativeDate(-2),
    updated_at: getRelativeDate(-1),
  },
  {
    id: 't-102',
    business_id: DEMO_BUSINESS.id,
    title: 'Contract signing with Zenith Publishing',
    description: 'Review SLA terms for high-volume offset catalog print run.',
    assignee_id: 'e1-asha',
    priority: 'CRITICAL',
    status: 'TODO',
    due_at: getRelativeDate(0, 18, 30), // Today Critical
    category: 'Management',
    created_at: getRelativeDate(-1),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-103',
    business_id: DEMO_BUSINESS.id,
    title: 'Client brochure mockups approval',
    description: 'Deliver tactile paper sample swatches and CMYK proofs to client.',
    assignee_id: 'e2-riya',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    due_at: getRelativeDate(0, 16, 0), // Today
    category: 'Design',
    created_at: getRelativeDate(-3),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-104',
    business_id: DEMO_BUSINESS.id,
    title: 'Restock Heidelberg UV ink cartridges',
    description: 'Cyan and Magenta running low on press line 2. Supplier delivery overdue.',
    assignee_id: 'e3-arjun',
    priority: 'HIGH',
    status: 'BLOCKED',
    due_at: getRelativeDate(-1, 12, 0), // Overdue + Blocked
    category: 'Operations',
    created_at: getRelativeDate(-4),
    updated_at: getRelativeDate(-1),
  },
  {
    id: 't-105',
    business_id: DEMO_BUSINESS.id,
    title: 'Quality check packaging boxes for Apex Corp',
    description: 'Inspect matte laminate finish and fold tolerances on 5,000 units.',
    assignee_id: 'e3-arjun',
    priority: 'MEDIUM',
    status: 'TODO',
    due_at: getRelativeDate(-2, 10, 0), // Overdue (causes Arjun to hit R4: >=2 overdue open tasks!)
    category: 'Operations',
    created_at: getRelativeDate(-5),
    updated_at: getRelativeDate(-2),
  },
  {
    id: 't-106',
    business_id: DEMO_BUSINESS.id,
    title: 'Brand proposal review for Horizon Hotels',
    description: 'Custom stationery and foil-stamped menu presentation.',
    assignee_id: 'e2-riya',
    priority: 'HIGH',
    status: 'TODO',
    due_at: getRelativeDate(1, 15, 0), // Tomorrow
    category: 'Design',
    created_at: getRelativeDate(-2),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-107',
    business_id: DEMO_BUSINESS.id,
    title: 'Social media visual assets for festival campaign',
    description: 'Posters and banner renders for promotional kickoff.',
    assignee_id: 'e2-riya',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    due_at: getRelativeDate(1, 18, 0), // Tomorrow
    category: 'Design',
    created_at: getRelativeDate(-1),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-108',
    business_id: DEMO_BUSINESS.id,
    title: 'Customer order check-ins and delivery tracking',
    description: 'Call 12 priority corporate accounts to confirm safe delivery.',
    assignee_id: 'e4-neha',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    due_at: getRelativeDate(3, 16, 0), // This week
    category: 'Customer Care',
    created_at: getRelativeDate(-1),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-109',
    business_id: DEMO_BUSINESS.id,
    title: 'Quarterly HR employee satisfaction check-in',
    description: 'Conduct feedback sessions and update employee wellness logs.',
    assignee_id: 'e1-asha',
    priority: 'LOW',
    status: 'TODO',
    due_at: getRelativeDate(4, 14, 0), // This week
    category: 'Management',
    created_at: getRelativeDate(-1),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-110',
    business_id: DEMO_BUSINESS.id,
    title: 'Fleet delivery van maintenance checkup',
    description: 'Brake fluid service and cargo shelf alignment for van #3.',
    assignee_id: 'e5-karan',
    priority: 'LOW',
    status: 'TODO',
    due_at: getRelativeDate(5, 11, 0), // This week
    category: 'Dispatch & Print',
    created_at: getRelativeDate(-2),
    updated_at: getRelativeDate(0),
  },
  {
    id: 't-111',
    business_id: DEMO_BUSINESS.id,
    title: 'Annual vendor contract renewal with PaperMill Direct',
    description: 'Signed wholesale agreement locked in for the next 12 months.',
    assignee_id: 'e1-asha',
    priority: 'HIGH',
    status: 'COMPLETED',
    due_at: getRelativeDate(-3, 17, 0),
    category: 'Management',
    created_at: getRelativeDate(-8),
    updated_at: getRelativeDate(-3),
    completed_at: getRelativeDate(-3, 16, 45),
  },
  {
    id: 't-112',
    business_id: DEMO_BUSINESS.id,
    title: 'Print exhibition booth banners for DesignWeek',
    description: '300gsm vinyl roller banners successfully printed and packed.',
    assignee_id: 'e5-karan',
    priority: 'MEDIUM',
    status: 'COMPLETED',
    due_at: getRelativeDate(-2, 14, 0),
    category: 'Dispatch & Print',
    created_at: getRelativeDate(-6),
    updated_at: getRelativeDate(-2),
    completed_at: getRelativeDate(-2, 13, 20),
  },
];
